USE team05
Create table Genre (
Mid int(5) PRIMARY KEY,
Genre VARCHAR(50) NOT NULL, 
Genre_s VARCHAR(100) NOT NULL,
FOREIGN KEY (Mid)
REFERENCES movie (Mid) ON UPDATE CASCADE
);
Create table Actor (
ACid int(11) PRIMARY KEY NOT NULL,
ACName varchar(100) NOT NULL,
Mid int(5) NOT NULL,
FOREIGN KEY (Mid)
REFERENCES movie(Mid) ON UPDATE CASCADE
);
Create table Review2 (
id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Uid VARCHAR(50),
Mid int(5) NOT NULL,
site_rate double(4,2) NOT NULL,
Text text,
FOREIGN KEY (Uid)
REFERENCES Users (Userid) ON UPDATE CASCADE,
FOREIGN KEY (Mid)
REFERENCES Movie (Mid) ON UPDATE CASCADE
);
CREATE TABLE REVIEW(
MID INT(5) PRIMARY KEY,
CRate DOUBLE(4,2),
ARate DOUBLE(4,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);
CREATE TABLE AGE_PR(
MID INT(5) PRIMARY KEY,
A10 DOUBLE(3,2),
A20 DOUBLE(3,2),
A30 DOUBLE(3,2),
A40 DOUBLE(3,2),
A50 DOUBLE(3,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);
CREATE TABLE GENDER_PR(
MID INT(5) PRIMARY KEY,
F DOUBLE(3,2),
M DOUBLE(3,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);