USE team05
CREATE TABLE movie(
MID INT(5) PRIMARY KEY,
title_kor VARCHAR(50) NOT NULL,
title_eng VARCHAR(50)
);
CREATE TABLE movie_info(
MID INT(5) PRIMARY KEY,
country VARCHAR(50) NOT NULL,
date INT(10),
director VARCHAR(50),
FOREIGN KEY (MID) REFERENCES movie(MID)
);
CREATE TABLE REVIEW(
MID INT(5) PRIMARY KEY,
CRate DOUBLE(4,2),
ARate DOUBLE(4,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);
Create table Genre(
Gid int(5) Primary key,
Genre varchar(50) NOT NULL
);
Create table Genrem (
Mid int(5) PRIMARY KEY,
Gid int(5), 
FOREIGN KEY (Mid)
REFERENCES movie (Mid) ON UPDATE CASCADE,
FOREIGN KEY (Gid) REFERENCES Genre(Gid)
);
CREATE TABLE AGE_PR(
MID INT(5) PRIMARY KEY,
A10 DOUBLE(3,2),
A20 DOUBLE(3,2),
A30 DOUBLE(3,2),
A40 DOUBLE(3,2),
A50 DOUBLE(3,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);
CREATE TABLE GENDER_PR(
MID INT(5) PRIMARY KEY,
F DOUBLE(3,2),
M DOUBLE(3,2),
FOREIGN KEY (MID) REFERENCES MOVIE(MID)
);
CREATE TABLE OTTs (
ott_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ott_name VARCHAR(50) NOT NULL
);
CREATE TABLE Users (
userid VARCHAR(50) NOT NULL PRIMARY KEY,
pwd VARCHAR(100) NOT NULL,
age_group INT,
Genres_prefer int(5) NOT NULL,
gender VARCHAR(1),
ott_prefer INT NOT NULL,
FOREIGN KEY (ott_prefer) REFERENCES OTTs (ott_id),
FOREIGN KEY (Genres_prefer) REFERENCES genre (Gid)
);
Create table Actor (
ACid int(11) PRIMARY KEY NOT NULL,
ACName varchar(100) NOT NULL,
Mid int(5) NOT NULL,
FOREIGN KEY (Mid)
REFERENCES movie(Mid) ON UPDATE CASCADE
);
CREATE TABLE OTT_Movies (
ott_id INT NOT NULL,
Mid INT(5) NOT NULL,
PRIMARY KEY (ott_id, Mid),
FOREIGN KEY(ott_id) REFERENCES OTTs(ott_id),
FOREIGN KEY(Mid) REFERENCES movie(Mid)
);
Create table Review2 (
id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Uid VARCHAR(50),
Mid int(5) NOT NULL,
site_rate double(4,2) NOT NULL,
Text text,
FOREIGN KEY (Uid)
REFERENCES Users (Userid) ON UPDATE CASCADE,
FOREIGN KEY (Mid)
REFERENCES Movie (Mid) ON UPDATE CASCADE
);
CREATE TABLE playlist(
PID INT(5) PRIMARY KEY,
pl_title VARCHAR(50) NOT NULL,
pl_creator VARCHAR(20) NOT NULL,
mov1 INT(5) NOT NULL,
mov2 INT(5),
mov3 INT(5),
mov4 INT(5),
FOREIGN KEY (mov1) REFERENCES movie(MID),
FOREIGN KEY (mov2) REFERENCES movie(MID),
FOREIGN KEY (mov3) REFERENCES movie(MID),
FOREIGN KEY (mov4) REFERENCES movie(MID)
);
CREATE TABLE fav_movies(
userid VARCHAR(50) NOT NULL PRIMARY KEY,
fav1 INT(5) NOT NULL,
fav2 INT(5),
fav3 INT(5),
FOREIGN KEY (userid) REFERENCES Users(userid),
FOREIGN KEY (fav1) REFERENCES movie(MID),
FOREIGN KEY (fav2) REFERENCES movie(MID),
FOREIGN KEY (fav3) REFERENCES movie(MID)
);