LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/movie.txt"
INTO TABLE Movie
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, title_kor, title_eng);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/movie_info.txt"
INTO TABLE Movie_info
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, COUNTRY, DATE, DIRECTOR);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/review.txt"
INTO TABLE review
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, CRATE, ARATE);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/genre.txt"
INTO TABLE genre
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(Gid, Genre);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/genrem.txt"
INTO TABLE genrem
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, Gid);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/age_pr.txt"
INTO TABLE age_pr
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, A10, A20, A30, A40, A50);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/gender_pr.txt"
INTO TABLE gender_pr
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(MID, F, M);
INSERT INTO OTTs VALUES (0001, 'NETFLIX');
INSERT INTO OTTs VALUES (0002, 'Watcha');
INSERT INTO OTTs VALUES (0003, 'wavve');
INSERT INTO OTTs VALUES (0004, 'Disney+');
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/actor.txt"
INTO TABLE actor
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(ACID, ACNAME, MID);
LOAD DATA LOCAL INFILE "C:/xampp/htdocs/team05/txt/ott_movies.txt"
INTO TABLE OTT_MOVIES
CHARACTER SET utf8
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
(ott_id, Mid);